### ISSUE TITLE
VALIDATE_INPUT_VCFS fails bc VarSeq allows whitespace in INFO fields

### ISSUE THREAD

**Issue by xguse** [ScottSnapperLab/prep-data-for-ibd-portal#1]
- [x] check to see if there is an export option from VarSeq that fixes this [@mlesfield]
- [x] if not, write a rule that converts or escapes the whitespace before sending the vcfs to  VALIDATE_INPUT_VCFS

**Comment by mlesfield** [comment]
We have some options as far as exporting vcfs. When I exported to the xlsxs I just grab all information as that is what Jodie did previously, and I figured better to have it and not need it than need it and not have it. I did the same for the vcfs, but in this case, less might be more.

When you get the time, drop by my computer, and we can figure out what info you actually need as much of it does not contain whitespaces. If we decide we need all of it, I can absolutely write something to remove the unnecessary whitespace.
